=====================================
# to add customization of the form login authentication in Spring boot

org.springframework.security:spring-security-web:3.2.5.RELEASE

Extended class to help form login get extra parameters in the http
request. 

It solves following issue:

http://stackoverflow.com/questions/16104228/how-implement-spring-security-when-login-page-having-more-field-apart-from-user?lq=1
http://stackoverflow.com/questions/23336770/spring-security-authentication-with-3-fields-instead-of-just-username-and-passwo?lq=1

1. Add a new token class HttpAuthenticationToken

It has a hashmap to store parameters/values from the http request. 

2. Use the new token class in the UsernamePasswordAuthenticationFilter class which will store all parameter/value pairs in the 
httpservletrequest.

3. The HttpAuthenticationToken class can be used in your customized authetication provider for your usage.

4. in the command line type: ./gradlew install, it will install the new build 3.2.5release in your local maven repository.

5. to force gradle to pick up the customized spring-security libs, put following in your spring boot build.gradle file:
repositories {
    mavenLocal()
	mavenCentral()
	maven { url "https://repo.spring.io/libs-milestone" }
}


configurations.all {
    // check for updates every build
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

dependencies {
    compile group: "org.springframework.security", name: "spring-security-web", version: "3.2.5.RELEASE", changing: true
}


It is a hack. But it gets the job done.
Another way to do it is following the link below. The author proposes a different approach, which I think is awesome.
http://www.future-processing.pl/blog/exploring-spring-boot-and-spring-security-custom-token-based-authentication-of-rest-services-with-spring-security-and-pinch-of-spring-java-configuration-and-spring-integration-testing/

==============================================


= Spring Security

Spring Security provides security services for the http://docs.spring.io[Spring IO Platform]. Spring Security 3.1 requires Spring 3.0.3 as
a minimum and also requires Java 5.

For a detailed list of features and access to the latest release, please visit http://spring.io/projects[Spring projects].

== Downloading Artifacts
See https://github.com/spring-projects/spring-framework/wiki/Downloading-Spring-artifacts[downloading Spring artifacts] for Maven repository information.

== Documentation
Be sure to read the http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/[Spring Security Reference].
Extensive JavaDoc for the Spring Security code is also available in the http://docs.spring.io/spring-security/site/docs/current/apidocs/[Spring Security API Documentation].

== Quick Start
We recommend you visit http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/[Spring Security Reference] and read the "Getting Started" page.

== Building from Source
Spring Security uses a http://gradle.org[Gradle]-based build system.
In the instructions below, http://vimeo.com/34436402[`./gradlew`] is invoked from the root of the source tree and serves as
a cross-platform, self-contained bootstrap mechanism for the build.

=== Prerequisites
http://help.github.com/set-up-git-redirect[Git] and the http://www.oracle.com/technetwork/java/javase/downloads[JDK7 build].

Be sure that your `JAVA_HOME` environment variable points to the `jdk1.7.0` folder extracted from the JDK download.

=== Check out sources
[indent=0]
----
git clone git@github.com:spring-projects/spring-security.git
----

=== Install all spring-\* jars into your local Maven cache
[indent=0]
----
./gradlew install
----

=== Compile and test; build all jars, distribution zips, and docs
[indent=0]
----
./gradlew build
----

Discover more commands with `./gradlew tasks`.
See also the https://github.com/spring-projects/spring-framework/wiki/Gradle-build-and-release-FAQ[Gradle build and release FAQ].

== Getting Support
Check out the http://stackoverflow.com/questions/tagged/spring-security[Spring Security tags on Stack Overflow].
http://spring.io/services[Commercial support] is available too.

== Contributing
http://help.github.com/send-pull-requests[Pull requests] are welcome; see the https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md[contributor guidelines] for details.

== License
Spring Security is Open Source software released under the
http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
